"""
Django settings for yunshublog project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rzsw5&9d%v=oi*pt)%zt!2&@_0^t8tmb4yh5fpla3db2#u6@af'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.yunshu.space']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'article',
    'userprofile',
    'password_reset',   #重置用户密码的轮子
    'comment',             #用户评论
    'ckeditor',         #富文本编辑器
    'taggit',           #标签功能
    'mptt',             #多级评论
    'notifications',    #消息通知
    'notice',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    #第三方登录
    'allauth.socialaccount.providers.github',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yunshublog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yunshublog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': 'F:\my.cnf',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')

EMAIL_HOST = 'smtp.qq.com'
EMAIL_HOST_USER = '515884472@qq.com'
EMAIL_HOST_PASSWORD = 'yjivnvaggnrxcaaj'
EMAIL_PORT = 25
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = '云舒小站 <515884472@qq.com>'

MEDIA_URL = '/media/'   #媒体文件地址
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

CKEDITOR_CONFIGS = {
    # django-ckeditor默认使用default配置
    'default': {
        # 编辑器宽度自适应
        'width':'auto',
        'height':'250px',
        # tab键转换空格数
        'tabSpaces': 4,
        # 工具栏风格
        'toolbar': 'Custom',
        # 工具栏按钮
        'toolbar_Custom': [
            # 表情 代码块
            ['Smiley', 'CodeSnippet'],
            # 字体风格
            ['Bold', 'Italic', 'Underline', 'RemoveFormat', 'Blockquote'],
            # 字体颜色
            ['TextColor', 'BGColor'],
            # 链接
            ['Link', 'Unlink'],
            # 列表
            ['NumberedList', 'BulletedList'],
            # 最大化
            ['Maximize']
        ],
        # 加入代码块插件
        'extraPlugins': ','.join(['codesnippet','prism','widget','lineutils',]),
    }
}

AUTHENTICATION_BACKENDS = (
    #django后台可独立于 allauth 登录
    'django.contrib.auth.backends.ModelBackend',
    #配置allauth独有的认证方法，如email 登录
    'allauth.account.auth_backends.AuthenticationBackend',
)

#设置站点
SITE_ID = 1
#登录成功后重定向地址
LOGIN_REDIRECT_URL = '/'


# LOGGING = {
# #     'version': 1,
# #     'disable_existing_loggers': False,
# #     'formatters': {
# #         'verbose': {
# #             'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
# #             'style': '{',
# #         },
# #         'simple': {
# #             'format': '{levelname} {message}',
# #             'style': '{',
# #         },
# #     },
# #     'filters': {
# #         'require_debug_true': {
# #             '()': 'django.utils.log.RequireDebugTrue',
# #         },
# #     },
# #     'handlers': {
# #         'console': {
# #             'level': 'INFO',
# #             'filters': ['require_debug_true'],
# #             'class': 'logging.StreamHandler',
# #             'formatter': 'simple'
# #         },
# #         'mail_admins': {
# #             'level': 'ERROR',
# #             'class': 'django.utils.log.AdminEmailHandler',
# #             'formatter': 'verbose',
# #         },
# #         'file': {
# #             'level': 'WARNING',
# #             # 'class': 'logging.FileHandler',
# #             'class': 'logging.handlers.TimedRotatingFileHandler',
# #             'when': 'midnight',
# #             'backupCount': 30,
# #             'filename': os.path.join(BASE_DIR, 'logs/debug.log'),
# #             'formatter': 'verbose',
# #         },
# #     },
# #     'loggers': {
# #         'django': {
# #             'handlers': ['console'],
# #             'propagate': True,
# #         },
# #         'django.request': {
# #             'handlers': ['file', 'mail_admins'],
# #             'level': 'WARNING',
# #             'propagate': False,
# #         },
# #     }
# # }